declare module "p5collide" {
  function collideRectCircle(
    rx: number,
    ry: number,
    rw: number,
    rh: number,
    cx: number,
    cy: number,
    diameter: number,
  ): boolean;
  function collideCirclePoly(
    cx: number,
    cy: number,
    diameter: number,
    vertices: any[],
  ): boolean;
  function collideRectPoly(
    rx: number,
    ry: number,
    rw: number,
    rh: number,
    vertices: any[],
  ): boolean;
  function collidePointCircle(
    x: number,
    y: number,
    cx: number,
    cy: number,
    diameter: number,
  ): boolean;
  function collidePointPoly(
    x: number,
    y: number,
    vertices: any[],
  ): boolean;
  function collidePointRect(
    x: number,
    y: number,
    rx: number,
    ry: number,
    rw: number,
    rh: number,
  ): boolean;
  function collideRectCircle(
    rx: number,
    ry: number,
    rw: number,
    rh: number,
    cx: number,
    cy: number,
    diameter: number,
  ): boolean;
}
